import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { MessageCircle, X, Send, Bot, User } from "lucide-react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";

interface ChatMessage {
  id: string;
  message: string;
  response: string;
  timestamp: Date;
  userId?: string;
}

export default function Chatbot() {
  const [isOpen, setIsOpen] = useState(false);
  const [message, setMessage] = useState("");
  const [messages, setMessages] = useState<ChatMessage[]>([]);

  // In a real app, get userId from authentication context
  const userId = "temp-user-id";

  // Fetch chat history
  const { data: chatHistory } = useQuery<ChatMessage[]>({
    queryKey: ["/api/chat", userId],
    enabled: isOpen,
  });

  // Send message mutation
  const sendMessageMutation = useMutation({
    mutationFn: async (messageData: { userId: string; message: string; response: string }) => {
      const response = await apiRequest("POST", "/api/chat", messageData);
      return response.json();
    },
    onSuccess: (data) => {
      setMessages(prev => [...prev, data]);
      setMessage("");
    },
  });

  const handleSendMessage = () => {
    if (!message.trim()) return;

    const messageData = {
      userId,
      message: message.trim(),
      response: "" // Will be generated by backend
    };

    sendMessageMutation.mutate(messageData);
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  const toggleChatbot = () => {
    setIsOpen(!isOpen);
    if (!isOpen && chatHistory) {
      setMessages(chatHistory);
    }
  };

  // Quick action buttons
  const quickActions = [
    "How can I prepare for JEE Main?",
    "Tell me about career options in engineering",
    "What colleges are best for computer science?",
    "Help me choose between NEET and JEE"
  ];

  const handleQuickAction = (action: string) => {
    setMessage(action);
  };

  return (
    <div className="fixed bottom-6 right-6 z-50">
      {/* Chat Window */}
      {isOpen && (
        <Card className="w-80 h-96 mb-4 shadow-2xl border border-border">
          <CardHeader className="bg-primary text-primary-foreground p-4 rounded-t-lg">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <Bot className="w-5 h-5" />
                <span className="font-semibold">MySaarthi Assistant</span>
              </div>
              <Button
                variant="ghost"
                size="sm"
                className="text-primary-foreground hover:bg-primary/20 h-8 w-8 p-0"
                onClick={toggleChatbot}
                data-testid="button-close-chatbot"
              >
                <X className="w-4 h-4" />
              </Button>
            </div>
          </CardHeader>
          
          <CardContent className="p-0 flex flex-col h-full">
            {/* Messages Area */}
            <ScrollArea className="flex-1 p-4 bg-muted/20" data-testid="chat-messages">
              <div className="space-y-4">
                {/* Welcome Message */}
                <div className="flex items-start space-x-2">
                  <div className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center">
                    <Bot className="w-4 h-4 text-primary" />
                  </div>
                  <div className="bg-primary/10 text-primary p-3 rounded-lg max-w-[220px] text-sm">
                    <p>Hi! I'm your MySaarthi assistant. I can help you with:</p>
                    <ul className="mt-2 space-y-1 text-xs">
                      <li>• Career guidance questions</li>
                      <li>• College selection advice</li>
                      <li>• Exam preparation tips</li>
                      <li>• Course recommendations</li>
                    </ul>
                  </div>
                </div>

                {/* Chat Messages */}
                {messages.map((msg, index) => (
                  <div key={index} className="space-y-2">
                    {/* User Message */}
                    <div className="flex items-start space-x-2 justify-end">
                      <div className="bg-card p-3 rounded-lg max-w-[220px] text-sm shadow-sm border border-border">
                        {msg.message}
                      </div>
                      <div className="w-8 h-8 bg-secondary/10 rounded-full flex items-center justify-center">
                        <User className="w-4 h-4 text-secondary" />
                      </div>
                    </div>
                    
                    {/* Bot Response */}
                    <div className="flex items-start space-x-2">
                      <div className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center">
                        <Bot className="w-4 h-4 text-primary" />
                      </div>
                      <div className="bg-primary/10 text-primary p-3 rounded-lg max-w-[220px] text-sm">
                        {msg.response}
                      </div>
                    </div>
                  </div>
                ))}

                {/* Loading indicator */}
                {sendMessageMutation.isPending && (
                  <div className="flex items-start space-x-2">
                    <div className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center">
                      <Bot className="w-4 h-4 text-primary" />
                    </div>
                    <div className="bg-primary/10 text-primary p-3 rounded-lg text-sm">
                      <div className="flex space-x-1">
                        <div className="w-2 h-2 bg-primary rounded-full animate-bounce"></div>
                        <div className="w-2 h-2 bg-primary rounded-full animate-bounce delay-75"></div>
                        <div className="w-2 h-2 bg-primary rounded-full animate-bounce delay-150"></div>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </ScrollArea>

            {/* Quick Actions */}
            {messages.length === 0 && (
              <div className="p-3 border-t border-border">
                <p className="text-xs text-muted-foreground mb-2">Quick questions:</p>
                <div className="space-y-1">
                  {quickActions.slice(0, 2).map((action, index) => (
                    <button
                      key={index}
                      className="text-xs text-left text-primary hover:bg-primary/5 p-2 rounded w-full transition-colors"
                      onClick={() => handleQuickAction(action)}
                      data-testid={`quick-action-${index}`}
                    >
                      {action}
                    </button>
                  ))}
                </div>
              </div>
            )}
            
            {/* Input Area */}
            <div className="p-4 border-t border-border bg-card">
              <div className="flex space-x-2">
                <Input
                  placeholder="Ask me anything about careers..."
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  onKeyPress={handleKeyPress}
                  className="flex-1 text-sm"
                  data-testid="input-chat-message"
                />
                <Button
                  size="sm"
                  onClick={handleSendMessage}
                  disabled={!message.trim() || sendMessageMutation.isPending}
                  data-testid="button-send-message"
                >
                  <Send className="w-4 h-4" />
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      )}
      
      {/* Toggle Button */}
      <Button
        className="w-14 h-14 rounded-full shadow-lg hover:shadow-xl transition-all hover:scale-110"
        onClick={toggleChatbot}
        data-testid="button-toggle-chatbot"
      >
        {isOpen ? (
          <X className="w-6 h-6" />
        ) : (
          <MessageCircle className="w-6 h-6" />
        )}
      </Button>
    </div>
  );
}
